/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Issues API
 * REST API for managing personal issues with JWT authentication
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuthResponse,
  CreateIssueRequest,
  IssueResponse,
  ListIssueResponse,
  ListParams,
  SignInRequest,
  SignUpRequest,
  UpdateIssueRequest
} from './model';

import { customInstance } from '../lib/axios-instance';




/**
 * @summary List issues
 */
export const list = (
    params?: ListParams,
 signal?: AbortSignal
) => {


      return customInstance<ListIssueResponse>(
      {url: `/issues`, method: 'GET',
        params, signal
    },
      );
    }



export const getListMutationOptions = <TError = ListIssueResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof list>>, TError,{params?: ListParams}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof list>>, TError,{params?: ListParams}, TContext> => {

const mutationKey = ['list'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof list>>, {params?: ListParams}> = (props) => {
          const {params} = props ?? {};

          return  list(params,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ListMutationResult = NonNullable<Awaited<ReturnType<typeof list>>>

    export type ListMutationError = ListIssueResponse

    /**
 * @summary List issues
 */
export const useList = <TError = ListIssueResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof list>>, TError,{params?: ListParams}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof list>>,
        TError,
        {params?: ListParams},
        TContext
      > => {
      return useMutation(getListMutationOptions(options), queryClient);
    }

/**
 * @summary Create an issue
 */
export const create = (
    createIssueRequest: CreateIssueRequest,
 signal?: AbortSignal
) => {


      return customInstance<IssueResponse>(
      {url: `/issues`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createIssueRequest, signal
    },
      );
    }




export const getCreateQueryKey = (createIssueRequest?: CreateIssueRequest,) => {
    return [
    'POST', `/issues`, createIssueRequest
    ] as const;
    }


export const getCreateQueryOptions = <TData = Awaited<ReturnType<typeof create>>, TError = IssueResponse>(createIssueRequest: CreateIssueRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof create>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCreateQueryKey(createIssueRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof create>>> = ({ signal }) => create(createIssueRequest, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof create>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CreateQueryResult = NonNullable<Awaited<ReturnType<typeof create>>>
export type CreateQueryError = IssueResponse


export function useCreate<TData = Awaited<ReturnType<typeof create>>, TError = IssueResponse>(
 createIssueRequest: CreateIssueRequest, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof create>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof create>>,
          TError,
          Awaited<ReturnType<typeof create>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCreate<TData = Awaited<ReturnType<typeof create>>, TError = IssueResponse>(
 createIssueRequest: CreateIssueRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof create>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof create>>,
          TError,
          Awaited<ReturnType<typeof create>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCreate<TData = Awaited<ReturnType<typeof create>>, TError = IssueResponse>(
 createIssueRequest: CreateIssueRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof create>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Create an issue
 */

export function useCreate<TData = Awaited<ReturnType<typeof create>>, TError = IssueResponse>(
 createIssueRequest: CreateIssueRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof create>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCreateQueryOptions(createIssueRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * @summary Create a new account
 */
export const signUp = (
    signUpRequest: SignUpRequest,
 signal?: AbortSignal
) => {


      return customInstance<AuthResponse>(
      {url: `/auth/sign-up`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: signUpRequest, signal
    },
      );
    }




export const getSignUpQueryKey = (signUpRequest?: SignUpRequest,) => {
    return [
    'POST', `/auth/sign-up`, signUpRequest
    ] as const;
    }


export const getSignUpQueryOptions = <TData = Awaited<ReturnType<typeof signUp>>, TError = AuthResponse>(signUpRequest: SignUpRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof signUp>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSignUpQueryKey(signUpRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof signUp>>> = ({ signal }) => signUp(signUpRequest, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof signUp>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SignUpQueryResult = NonNullable<Awaited<ReturnType<typeof signUp>>>
export type SignUpQueryError = AuthResponse


export function useSignUp<TData = Awaited<ReturnType<typeof signUp>>, TError = AuthResponse>(
 signUpRequest: SignUpRequest, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof signUp>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof signUp>>,
          TError,
          Awaited<ReturnType<typeof signUp>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSignUp<TData = Awaited<ReturnType<typeof signUp>>, TError = AuthResponse>(
 signUpRequest: SignUpRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof signUp>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof signUp>>,
          TError,
          Awaited<ReturnType<typeof signUp>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSignUp<TData = Awaited<ReturnType<typeof signUp>>, TError = AuthResponse>(
 signUpRequest: SignUpRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof signUp>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Create a new account
 */

export function useSignUp<TData = Awaited<ReturnType<typeof signUp>>, TError = AuthResponse>(
 signUpRequest: SignUpRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof signUp>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSignUpQueryOptions(signUpRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * @summary Authenticate and get an access token
 */
export const signIn = (
    signInRequest: SignInRequest,
 signal?: AbortSignal
) => {


      return customInstance<AuthResponse>(
      {url: `/auth/sign-in`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: signInRequest, signal
    },
      );
    }




export const getSignInQueryKey = (signInRequest?: SignInRequest,) => {
    return [
    'POST', `/auth/sign-in`, signInRequest
    ] as const;
    }


export const getSignInQueryOptions = <TData = Awaited<ReturnType<typeof signIn>>, TError = AuthResponse>(signInRequest: SignInRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof signIn>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSignInQueryKey(signInRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof signIn>>> = ({ signal }) => signIn(signInRequest, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof signIn>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SignInQueryResult = NonNullable<Awaited<ReturnType<typeof signIn>>>
export type SignInQueryError = AuthResponse


export function useSignIn<TData = Awaited<ReturnType<typeof signIn>>, TError = AuthResponse>(
 signInRequest: SignInRequest, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof signIn>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof signIn>>,
          TError,
          Awaited<ReturnType<typeof signIn>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSignIn<TData = Awaited<ReturnType<typeof signIn>>, TError = AuthResponse>(
 signInRequest: SignInRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof signIn>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof signIn>>,
          TError,
          Awaited<ReturnType<typeof signIn>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSignIn<TData = Awaited<ReturnType<typeof signIn>>, TError = AuthResponse>(
 signInRequest: SignInRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof signIn>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Authenticate and get an access token
 */

export function useSignIn<TData = Awaited<ReturnType<typeof signIn>>, TError = AuthResponse>(
 signInRequest: SignInRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof signIn>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSignInQueryOptions(signInRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * @summary Get an issue by ID
 */
export const get = (
    id: string,
 signal?: AbortSignal
) => {


      return customInstance<IssueResponse>(
      {url: `/issues/${id}`, method: 'GET', signal
    },
      );
    }



export const getGetMutationOptions = <TError = IssueResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof get>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof get>>, TError,{id: string}, TContext> => {

const mutationKey = ['get'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof get>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  get(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetMutationResult = NonNullable<Awaited<ReturnType<typeof get>>>

    export type GetMutationError = IssueResponse

    /**
 * @summary Get an issue by ID
 */
export const useGet = <TError = IssueResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof get>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof get>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getGetMutationOptions(options), queryClient);
    }

/**
 * @summary Delete an issue
 */
export const _delete = (
    id: string,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/issues/${id}`, method: 'DELETE', signal
    },
      );
    }




export const getDeleteQueryKey = (id: string,) => {
    return [
    'DELETE', `/issues/${id}`
    ] as const;
    }


export const getDeleteQueryOptions = <TData = Awaited<ReturnType<typeof _delete>>, TError = void>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof _delete>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDeleteQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof _delete>>> = ({ signal }) => _delete(id, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof _delete>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type _DeleteQueryResult = NonNullable<Awaited<ReturnType<typeof _delete>>>
export type _DeleteQueryError = void


export function useDelete<TData = Awaited<ReturnType<typeof _delete>>, TError = void>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof _delete>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof _delete>>,
          TError,
          Awaited<ReturnType<typeof _delete>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDelete<TData = Awaited<ReturnType<typeof _delete>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof _delete>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof _delete>>,
          TError,
          Awaited<ReturnType<typeof _delete>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDelete<TData = Awaited<ReturnType<typeof _delete>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof _delete>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Delete an issue
 */

export function useDelete<TData = Awaited<ReturnType<typeof _delete>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof _delete>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDeleteQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * @summary Update an issue
 */
export const update = (
    id: string,
    updateIssueRequest: UpdateIssueRequest,
 signal?: AbortSignal
) => {


      return customInstance<IssueResponse>(
      {url: `/issues/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateIssueRequest, signal
    },
      );
    }




export const getUpdateQueryKey = (id: string,
    updateIssueRequest?: UpdateIssueRequest,) => {
    return [
    'PATCH', `/issues/${id}`, updateIssueRequest
    ] as const;
    }


export const getUpdateQueryOptions = <TData = Awaited<ReturnType<typeof update>>, TError = IssueResponse>(id: string,
    updateIssueRequest: UpdateIssueRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof update>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUpdateQueryKey(id,updateIssueRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof update>>> = ({ signal }) => update(id,updateIssueRequest, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof update>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UpdateQueryResult = NonNullable<Awaited<ReturnType<typeof update>>>
export type UpdateQueryError = IssueResponse


export function useUpdate<TData = Awaited<ReturnType<typeof update>>, TError = IssueResponse>(
 id: string,
    updateIssueRequest: UpdateIssueRequest, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof update>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof update>>,
          TError,
          Awaited<ReturnType<typeof update>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUpdate<TData = Awaited<ReturnType<typeof update>>, TError = IssueResponse>(
 id: string,
    updateIssueRequest: UpdateIssueRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof update>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof update>>,
          TError,
          Awaited<ReturnType<typeof update>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUpdate<TData = Awaited<ReturnType<typeof update>>, TError = IssueResponse>(
 id: string,
    updateIssueRequest: UpdateIssueRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof update>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Update an issue
 */

export function useUpdate<TData = Awaited<ReturnType<typeof update>>, TError = IssueResponse>(
 id: string,
    updateIssueRequest: UpdateIssueRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof update>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUpdateQueryOptions(id,updateIssueRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * @summary Mark an issue as completed
 */
export const complete = (
    id: string,
 signal?: AbortSignal
) => {


      return customInstance<IssueResponse>(
      {url: `/issues/${id}/complete`, method: 'PATCH', signal
    },
      );
    }




export const getCompleteQueryKey = (id: string,) => {
    return [
    'PATCH', `/issues/${id}/complete`
    ] as const;
    }


export const getCompleteQueryOptions = <TData = Awaited<ReturnType<typeof complete>>, TError = IssueResponse>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof complete>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCompleteQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof complete>>> = ({ signal }) => complete(id, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof complete>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CompleteQueryResult = NonNullable<Awaited<ReturnType<typeof complete>>>
export type CompleteQueryError = IssueResponse


export function useComplete<TData = Awaited<ReturnType<typeof complete>>, TError = IssueResponse>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof complete>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof complete>>,
          TError,
          Awaited<ReturnType<typeof complete>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useComplete<TData = Awaited<ReturnType<typeof complete>>, TError = IssueResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof complete>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof complete>>,
          TError,
          Awaited<ReturnType<typeof complete>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useComplete<TData = Awaited<ReturnType<typeof complete>>, TError = IssueResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof complete>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Mark an issue as completed
 */

export function useComplete<TData = Awaited<ReturnType<typeof complete>>, TError = IssueResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof complete>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCompleteQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







