/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Issues API
 * REST API for managing personal issues with JWT authentication
 * OpenAPI spec version: v1
 */

export interface CreateIssueRequest {
  /**
     * @minLength 0
     * @maxLength 100
     */
  title: string;
  description?: string;
}
