/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Issues API
 * REST API for managing personal issues with JWT authentication
 * OpenAPI spec version: v1
 */

export interface IssueResponse {
  id?: string;
  userId?: string;
  title?: string;
  description?: string;
  completed?: boolean;
  createdAt?: string;
  updatedAt?: string;
}
