/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Issues API
 * REST API for managing personal issues with JWT authentication
 * OpenAPI spec version: v1
 */
import type { IssueResponse } from './issueResponse.ts';

export interface ListIssueResponse {
  items?: IssueResponse[];
  nextCursor?: string;
  hasMore?: boolean;
}
