/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Issues API
 * REST API for managing personal issues with JWT authentication
 * OpenAPI spec version: v1
 */

export type ListParams = {
completed?: boolean;
cursor?: string;
limit?: number;
};
