/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Issues API
 * REST API for managing personal issues with JWT authentication
 * OpenAPI spec version: v1
 */

export interface SignUpRequest {
  email?: string;
  /** @minLength 1 */
  name: string;
  /**
     * @minLength 8
     * @maxLength 2147483647
     */
  password?: string;
}
